export const TOTAL_FRAMES = 205;
export const SCROLL_MULTIPLIER = 18;
export const SCROLL_HEIGHT = TOTAL_FRAMES * SCROLL_MULTIPLIER;

export const MOBILE_TOTAL_FRAMES = 228;
export const MOBILE_SCROLL_HEIGHT = MOBILE_TOTAL_FRAMES * SCROLL_MULTIPLIER;

export const PPF_TOTAL_FRAMES = 240;
export const PPF_MOBILE_TOTAL_FRAMES = 129;
export const PPF_SCROLL_MULTIPLIER = 15;
export const PPF_SCROLL_HEIGHT = PPF_TOTAL_FRAMES * PPF_SCROLL_MULTIPLIER;

export const TINT_TOTAL_FRAMES = 199;
export const TINT_MOBILE_TOTAL_FRAMES = 181;
export const TINT_SCROLL_MULTIPLIER = 15;
export const TINT_SCROLL_HEIGHT = TINT_TOTAL_FRAMES * TINT_SCROLL_MULTIPLIER;
export const TINT_MOBILE_SCROLL_HEIGHT = TINT_MOBILE_TOTAL_FRAMES * TINT_SCROLL_MULTIPLIER;

export const VINYL_TOTAL_FRAMES = 240;
export const VINYL_MOBILE_TOTAL_FRAMES = 240;
export const VINYL_SCROLL_MULTIPLIER = 15;
export const VINYL_SCROLL_HEIGHT = VINYL_TOTAL_FRAMES * VINYL_SCROLL_MULTIPLIER;
export const VINYL_MOBILE_SCROLL_HEIGHT = VINYL_MOBILE_TOTAL_FRAMES * VINYL_SCROLL_MULTIPLIER;

export const STICKERS_TOTAL_FRAMES = 163;
export const STICKERS_MOBILE_TOTAL_FRAMES = 231;
export const STICKERS_SCROLL_HEIGHT = 5000;
export const STICKERS_MOBILE_SCROLL_HEIGHT = 3500;

export const CERAMIC_TOTAL_FRAMES = 69;
export const CERAMIC_MOBILE_TOTAL_FRAMES = 162;
export const CERAMIC_SCROLL_HEIGHT = 5500;
export const CERAMIC_MOBILE_SCROLL_HEIGHT = 3000;
